# Generated by Django 2.2.9 on 2020-01-19 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicepage",
            name="service_image",
            field=models.ForeignKey(
                help_text="This Image will be used on the service listing Page and will be cropped to 573px by 369px on this page.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.Image",
            ),
        ),
    ]
