# Generated by Django 2.2.9 on 2020-01-13 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0001_squashed_0021"),
        ("wagtailcore", "0041_group_collection_permissions_verbose_name_plural"),
        ("home", "0002_create_homepage"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="banner_background_image",
            field=models.ForeignKey(
                blank=True,
                help_text="The banner background image",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.Image",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="button",
            field=models.ForeignKey(
                blank=True,
                help_text="Select an optional text to link to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.Page",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="button_text",
            field=models.CharField(
                default="Read More", help_text="Read mor text", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="lead_text",
            field=models.CharField(
                blank=True,
                help_text="Subheading text under the banner title",
                max_length=140,
            ),
        ),
    ]
