# Generated by Django 2.2.9 on 2020-01-14 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_auto_20200113_1521"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="button_text",
            field=models.CharField(
                default="Read More", help_text="Read more ", max_length=50
            ),
        ),
    ]
